import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import { example01, example02, example03 } from './examples';

export default function Home() {
  const [exampleDataList, setExampleDataList] = useState<boolean[]>([]);

  useEffect(() => {
    const ex1 = example01();
    const ex2 = example02();
    const ex3 = example03();
    const list = [ex1, ex2, ex3];
    setExampleDataList(list);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Test for device check</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Test for device check</h1>

        <div className={styles.description}>
          <table className={styles.table}>
            <tbody>
              {exampleDataList.map((item, id) => {
                return (
                  <tr key={id}>
                    <td>
                      <strong>EX{id + 1}</strong>
                    </td>
                    <td>You are using: </td>
                    <td>
                      <code className={styles.code}>
                        {item ? 'mobile' : 'pc'}
                      </code>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
